### ISSUE TITLE
Could't open the link of .tgz and hdf5!  help me please!

### ISSUE THREAD

**Issue by songsonggithub** [aimagelab/show-control-and-tell#7]
When I clik the link, it will return me like the under!

Forbidden
You don't have permission to access /releases/show-control-and-tell/dataset_coco.tgz on this server.
Apache/2.4.29 (Ubuntu) Server at ailb-web.ing.unimore.it Port 80

**Comment by baraldilorenzo** [comment]
Hi, thanks for pointing this out!
All the download links should be working now. If you have any issues, do not hesitate to reopen the issue.

Best,
Lorenzo.

**Comment by songsonggithub** [comment]
Thanks, I try and ok now!

**Comment by irolaina** [comment]
The links still show permission issues for me.. Any chance you could make the annotations available? Thanks!

**Comment by songsonggithub** [comment]
Another link：Google cloud，it is under the .gz link，you can see，but you need vpn.


发自我的iPhone

------------------ Original ------------------
